name: CI/CD - serpro-consult-api

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Executar testes
        run: mvn test

      - name: Upload do artefato JAR
        uses: actions/upload-artifact@v4
        with:
          name: serpro-api-jar
          path: target/*.jar

